#!/usr/bin/env bash
# This script is displaying numbers from 1 to 100 and printing message when the number is multiple.

for ((num=0 ; num<=100 ; num++))
do
  if ((num % 3 == 0 && num % 5 == 0)); then
    echo "FizzBuzz"
    elif ((num % 3 == 0)); then
      echo "Fizz"
    elif ((num % 5 == 0)); then
      echo "Buzz"
  else
    echo $num	
  fi	  
done
