#!/usr/bin/env bash
#This script is displaying the content of the current directory, part ot the name the first dash in displayed.

directorio="."

for archivo in "$directorio"/*
do
  nombre_archivo=$(basename "$archivo")
  if [[ "$nombre_archivo" == *-* ]]; then
    parte_despues_guion=$(echo "$nombre_archivo" | cut -d '-' -f 2-)
    echo "$parte_despues_guion"
  fi
done
