#!/usr/bin/env bash
#This script is displaying the content of the current directory,
#where only the part of the name after the first dash is displayed.

# Directorio a listar
directorio="."

# Ciclo for para iterar sobre cada archivo en el directorio
for archivo in "$directorio"/*
do
  echo "$(basename "$archivo")"
done
