#!/usr/bin/env bash
#This script is displaying information about the school file.

# Nombre del archivo
archivo="school"

# Verifica si el archivo existe
if [ -e "$archivo" ]; then
  echo "'$archivo' file exists"
  
# Verifica si el archivo está vacío
  if [ -s "$archivo" ]; then
    echo "'$archivo' file is not empty"
  else
    echo "'$archivo' file is empty"
  fi

  # Verifica el tipo de archivo
  if [ -f "$archivo" ]; then
    echo "'$archivo' is a regular file"
  fi
else
  echo "'$archivo' file does not exist"
fi
