#!/usr/bin/env bash
# This script is displaying the content of the file /etc/passwd

# Abrir el archivo /etc/passwd para lectura
while read -r line; do echo "$line" | cut -d: -f1,3,6;  
  cleaned_homedir=${homedir#/home/"$username"}
  echo "$username:$userid:$cleaned_homedir"
done < /etc/passwd
