#!/usr/bin/env bash
#This script stops 4-to_infinity_and_beyond proces with kill.

# Find the PID of the process named 4-to_infinity_and_beyond
pid=$(pgrep -f 4-to_infinity_and_beyond)

# Check if the process is running
if [ -z "$pid" ]; then
  echo "No 4-to_infinity_and_beyond process found."
else
  # Kill the process
  kill "$pid"
  echo "4-to_infinity_and_beyond process with PID $pid has been stopped."
fi

